version: "3.7"

# Will use the hostname when talking between services on the same network
services:

  portal-ui:
    hostname: portal-ui
    container_name: portal-ui
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - HOST_GID=${HOST_GID:-1002}
      - HOST_UID=${HOST_UID:-1002}
    init: true
    restart: always
    volumes:
      # Mount the logging to container
      - "../log:/usr/src/app/log"
    networks:
      - sennet_docker_network
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: ${PORTAL_UI_CLOUDWATCH_LOG_GROUP:?err}

networks:
  # This is the network created by gateway to enable communication between multiple docker-compose projects
  sennet_docker_network:
    external: true
